name = "LowRankSpectral"
uuid = "0e4bc44e-1c4b-400b-bc5c-d02b80ef6c17"
authors = ["Charles Colley ccolley@purdue.edu"]
version = "0.1.0"

[deps]
MatrixNetworks = "4f449596-a032-5618-b826-5a251cb6dc11"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1"
